// states/ct/games.ts
import { GameData } from "@/types/GameData";
import MegaMillionsLogo from "@/assets/logos/ct/megamillions.svg";
import PowerballLogo from "@/assets/logos/ct/powerball.svg";
import ClassicLottoLogo from "@/assets/logos/ct/classiclotto.svg";
import Cash5Logo from "@/assets/logos/ct/cash5.svg";
import LuckyForLifeLogo from "@/assets/logos/ct/luckyforlife.svg";
import Play4DayLogo from "@/assets/logos/ct/play4day.svg";
import Play4NightLogo from "@/assets/logos/ct/play4night.svg";
import Play3DayLogo from "@/assets/logos/ct/play3day.svg";
import Play3NightLogo from "@/assets/logos/ct/play3night.svg";

// MOCK CT GAMES
export async function fetchConnecticutGames(): Promise<GameData[]> {
  return [
    // Mega Millions
    {
      id: "megamillions_ct",
      name: "Mega Millions",
      slug: "megamillions",
      logo: MegaMillionsLogo,
      jackpot: "$143 Million",
      cashValue: "$66.8 Million",
      drawTime: "23:00:00",
      drawDate: "Tue, Jun 11, 2025",
      numbers: ["02", "13", "22", "40", "62", "15"],
      bonusNumber: "15",
      powerPlay: "3x",
      result: "No Jackpot Winners",
      config_ui: {
        borderColor: "#0E4CA1",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#0E4CA1", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FFD700", "#B8860B"],
        lastBallTextColor: "#fff",
        playButtonColor: "#0E4CA1",
        playButtonBorder: "#EE3E33",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Powerball
    {
      id: "powerball_ct",
      name: "Powerball",
      slug: "powerball",
      logo: PowerballLogo,
      jackpot: "$95 Million",
      cashValue: "$45.7 Million",
      drawTime: "22:59:00",
      drawDate: "Wed, Jun 12, 2025",
      numbers: ["04", "18", "34", "55", "61", "20"],
      bonusNumber: "20",
      powerPlay: "2x",
      result: "No Jackpot Winners",
      config_ui: {
        borderColor: "#C7102E",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#C7102E", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FF6666", "#B1001C"],
        lastBallTextColor: "#fff",
        playButtonColor: "#C7102E",
        playButtonBorder: "#0E4CA1",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Lotto!
    {
      id: "classiclotto_ct",
      name: "Lotto!",
      slug: "classiclotto",
      logo: ClassicLottoLogo,
      jackpot: "$3.8 Million",
      cashValue: "$3.8 Million",
      drawTime: "22:00:00",
      drawDate: "Tue, Jun 11, 2025",
      numbers: ["10", "18", "26", "34", "45", "48"],
      bonusNumber: "",
      powerPlay: "",
      result: "No Jackpot Winners",
      config_ui: {
        borderColor: "#2e3092",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFF", "#2e3092", "#FFF"],
        ballGradient: ["#FFFFFF", "#FFD700"],
        ballTextColor: "#001e62",
        lastBallGradient: ["#FFD700", "#2e3092"],
        lastBallTextColor: "#2e3092",
        playButtonColor: "#2e3092",
        playButtonBorder: "#FFD700",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Cash5
    {
      id: "cash5_ct",
      name: "Cash5",
      slug: "cash5",
      logo: Cash5Logo,
      jackpot: "$100,000",
      cashValue: "$100,000",
      drawTime: "22:00:00",
      drawDate: "Tue, Jun 11, 2025",
      numbers: ["02", "17", "21", "28", "31"],
      bonusNumber: "",
      powerPlay: "",
      result: "No Jackpot Winners",
      config_ui: {
        borderColor: "#46b149",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFF", "#46b149", "#FFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#206620",
        lastBallGradient: ["#FFFFFF", "#46b149"],
        lastBallTextColor: "#206620",
        playButtonColor: "#46b149",
        playButtonBorder: "#206620",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Lucky for Life
    {
      id: "luckyforlife_ct",
      name: "Lucky for Life",
      slug: "luckyforlife",
      logo: LuckyForLifeLogo,
      jackpot: "$1,000 a Day for Life",
      cashValue: "",
      drawTime: "22:30:00",
      drawDate: "Tue, Jun 11, 2025",
      numbers: ["06", "12", "28", "29", "47", "18"],
      bonusNumber: "18",
      powerPlay: "",
      result: "No Jackpot Winners",
      config_ui: {
        borderColor: "#3b9853",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFF", "#3b9853", "#FFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#155939",
        lastBallGradient: ["#FFFFFF", "#3b9853"],
        lastBallTextColor: "#fff",
        playButtonColor: "#3b9853",
        playButtonBorder: "#155939",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Play4 Day
    {
      id: "play4day_ct",
      name: "Play4 Day",
      slug: "play4day",
      logo: Play4DayLogo,
      jackpot: "$5,000",
      cashValue: "$5,000",
      drawTime: "13:00:00",
      drawDate: "Tue, Jun 11, 2025",
      numbers: ["1", "2", "3", "4"],
      bonusNumber: "",
      powerPlay: "",
      result: "Daytime Drawing",
      config_ui: {
        borderColor: "#fecd19",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFF", "#fecd19", "#FFF"],
        ballGradient: ["#FFFFFF", "#fecd19"],
        ballTextColor: "#0075bc",
        lastBallGradient: ["#fecd19", "#0075bc"],
        lastBallTextColor: "#fff",
        playButtonColor: "#fecd19",
        playButtonBorder: "#0075bc",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Play4 Night
    {
      id: "play4night_ct",
      name: "Play4 Night",
      slug: "play4night",
      logo: Play4NightLogo,
      jackpot: "$5,000",
      cashValue: "$5,000",
      drawTime: "22:00:00",
      drawDate: "Tue, Jun 11, 2025",
      numbers: ["7", "8", "9", "5"],
      bonusNumber: "",
      powerPlay: "",
      result: "Night Drawing",
      config_ui: {
        borderColor: "#0075bc",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFF", "#0075bc", "#FFF"],
        ballGradient: ["#FFFFFF", "#0075bc"],
        ballTextColor: "#fecd19",
        lastBallGradient: ["#0075bc", "#fecd19"],
        lastBallTextColor: "#fff",
        playButtonColor: "#0075bc",
        playButtonBorder: "#fecd19",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Play3 Day
    {
      id: "play3day_ct",
      name: "Play3 Day",
      slug: "play3day",
      logo: Play3DayLogo,
      jackpot: "$500",
      cashValue: "$500",
      drawTime: "13:00:00",
      drawDate: "Tue, Jun 11, 2025",
      numbers: ["1", "5", "9"],
      bonusNumber: "",
      powerPlay: "",
      result: "Daytime Drawing",
      config_ui: {
        borderColor: "#fecd19",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFF", "#fecd19", "#FFF"],
        ballGradient: ["#FFFFFF", "#fecd19"],
        ballTextColor: "#0075bc",
        lastBallGradient: ["#fecd19", "#0075bc"],
        lastBallTextColor: "#fff",
        playButtonColor: "#fecd19",
        playButtonBorder: "#0075bc",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Play3 Night
    {
      id: "play3night_ct",
      name: "Play3 Night",
      slug: "play3night",
      logo: Play3NightLogo,
      jackpot: "$500",
      cashValue: "$500",
      drawTime: "22:00:00",
      drawDate: "Tue, Jun 11, 2025",
      numbers: ["6", "8", "2"],
      bonusNumber: "",
      powerPlay: "",
      result: "Night Drawing",
      config_ui: {
        borderColor: "#0075bc",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFF", "#0075bc", "#FFF"],
        ballGradient: ["#FFFFFF", "#0075bc"],
        ballTextColor: "#fecd19",
        lastBallGradient: ["#0075bc", "#fecd19"],
        lastBallTextColor: "#fff",
        playButtonColor: "#0075bc",
        playButtonBorder: "#fecd19",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
  ];
}
