// states/NY/games.ts
import { GameData } from "@/types/GameData";
import PowerballLogo from "@/assets/logos/NY/powerball.svg";
import MegaMillionsLogo from "@/assets/logos/NY/megamillions.svg";
import Cash4LifeLogo from "@/assets/logos/NY/cash4life.svg";
import NYLottoLogo from "@/assets/logos/NY/nylotto.svg";
import Win4MiddayLogo from "@/assets/logos/NY/win4midday.svg";
import Win4EveningLogo from "@/assets/logos/NY/win4evening.svg";
import NumbersMiddayLogo from "@/assets/logos/NY/numbersmidday.svg";
import NumbersEveningLogo from "@/assets/logos/NY/numbersevening.svg";
import Take5MiddayLogo from "@/assets/logos/NY/take5midday.svg";
import Take5EveningLogo from "@/assets/logos/NY/take5evening.svg";
import Pick10Logo from "@/assets/logos/NY/pick10.svg";

export async function fetchNewYorkGames(): Promise<GameData[]> {
  return [
    {
      id: "powerball_ny",
      name: "Powerball",
      slug: "powerball",
      logo: PowerballLogo,
      jackpot: "$95 Million",
      cashValue: "$45.7 Million",
      drawTime: "Mon, Wed, Sat 10:59 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["05", "09", "22", "34", "51", "10"],
      bonusNumber: "10",
      powerPlay: "2x",
      result: "No Jackpot Winner | 1 Match 5 Winner | NY",
      config_ui: {
        borderColor: "#C7102E",
        gradient: ["#FFFFFF", "#C7102E", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FF6666", "#B1001C"],
        playButtonColor: "#000",
        playButtonBorder: "#C7102E",
        ballTextColor: "#101820",
        lastBallTextColor: "#fff",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "megamillions_ny",
      name: "Mega Millions",
      slug: "megamillions",
      logo: MegaMillionsLogo,
      jackpot: "$143 Million",
      cashValue: "$66.8 Million",
      drawTime: "Tue & Fri 11:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "22", "33", "44", "55", "16"],
      bonusNumber: "16",
      powerPlay: "3x",
      result: "No Jackpot Winners | 3 Match 5 Winner | NY",
      config_ui: {
        borderColor: "#05549E",
        gradient: ["#FFFFFF", "#0E4CA1", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FFDE1B", "#B77302"],
        playButtonColor: "#0E4CA1",
        playButtonBorder: "#EE3E33",
        ballTextColor: "#101820",
        lastBallTextColor: "#fff",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "cash4life_ny",
      name: "Cash4Life",
      slug: "cash4life",
      logo: Cash4LifeLogo,
      jackpot: "$7,000/Week for Life",
      cashValue: "$3,800,000",
      drawTime: "Daily 9:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["02", "13", "24", "31", "52", "04"],
      bonusNumber: "04",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#2D7F67",
        gradient: ["#FFFFFF", "#2D7F67", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#5160AC", "#3D425E"],
        playButtonColor: "#3E4982",
        playButtonBorder: "#2D7F67",
        ballTextColor: "#101820",
        lastBallTextColor: "#fff",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "nylotto_ny",
      name: "NY Lotto",
      slug: "nylotto",
      logo: NYLottoLogo,
      jackpot: "$12.3 Million",
      cashValue: "$7.5 Million",
      drawTime: "Wed & Sat 8:15 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["11", "19", "24", "38", "43", "48"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#D31245",
        gradient: ["#FFFFFF", "#D31245", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#F53C6D", "#A4143A"],
        playButtonColor: "#D31245",
        playButtonBorder: "#005596",
        ballTextColor: "#101820",
        lastBallTextColor: "#fff",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "win4_midday_ny",
      name: "Win 4 Midday",
      slug: "win4_midday",
      logo: Win4MiddayLogo,
      jackpot: "$5,000",
      cashValue: "$5,000",
      drawTime: "Daily 2:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["02", "07", "08", "10"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#7E0C6E",
        gradient: ["#FFFFFF", "#7E0C6E", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        playButtonColor: "#7E0C6E",
        playButtonBorder: "#7E0C6E",
        ballTextColor: "#101820",
        lastBallTextColor: "#101820",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "win4_evening_ny",
      name: "Win 4 Evening",
      slug: "win4_evening",
      logo: Win4EveningLogo,
      jackpot: "$5,000",
      cashValue: "$5,000",
      drawTime: "Daily 7:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["04", "07", "12", "15"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#7E0C6E",
        gradient: ["#FFFFFF", "#7E0C6E", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        playButtonColor: "#7E0C6E",
        playButtonBorder: "#7E0C6E",
        ballTextColor: "#101820",
        lastBallTextColor: "#101820",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "numbers_midday_ny",
      name: "Numbers Midday",
      slug: "numbers_midday",
      logo: NumbersMiddayLogo,
      jackpot: "$500",
      cashValue: "$500",
      drawTime: "Daily 2:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "05", "09"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#2E73B5",
        gradient: ["#FFFFFF", "#2E73B5", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        playButtonColor: "#2E73B5",
        playButtonBorder: "#2E73B5",
        ballTextColor: "#101820",
        lastBallTextColor: "#101820",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "numbers_evening_ny",
      name: "Numbers Evening",
      slug: "numbers_evening",
      logo: NumbersEveningLogo,
      jackpot: "$500",
      cashValue: "$500",
      drawTime: "Daily 7:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "07", "09"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#2E73B5",
        gradient: ["#FFFFFF", "#2E73B5", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        playButtonColor: "#2E73B5",
        playButtonBorder: "#2E73B5",
        ballTextColor: "#101820",
        lastBallTextColor: "#101820",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "take5_midday_ny",
      name: "Take 5 Midday",
      slug: "take5_midday",
      logo: Take5MiddayLogo,
      jackpot: "$20,000",
      cashValue: "$20,000",
      drawTime: "Daily 2:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["02", "08", "13", "19", "24"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#CA3092",
        gradient: ["#FFFFFF", "#CA3092", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        playButtonColor: "#00928F",
        playButtonBorder: "#CA3092",
        ballTextColor: "#101820",
        lastBallTextColor: "#101820",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "take5_evening_ny",
      name: "Take 5 Evening",
      slug: "take5_evening",
      logo: Take5EveningLogo,
      jackpot: "$20,000",
      cashValue: "$20,000",
      drawTime: "Daily 7:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["06", "15", "23", "25", "29"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#CA3092",
        gradient: ["#FFFFFF", "#CA3092", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        playButtonColor: "#00928F",
        playButtonBorder: "#CA3092",
        ballTextColor: "#101820",
        lastBallTextColor: "#101820",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "pick10_ny",
      name: "Pick 10",
      slug: "pick10",
      logo: Pick10Logo,
      jackpot: "$500,000",
      cashValue: "$500,000",
      drawTime: "Daily 12:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: [
        "02",
        "08",
        "17",
        "22",
        "30",
        "35",
        "41",
        "45",
        "52",
        "67",
        "02",
        "08",
        "17",
        "22",
        "30",
        "35",
        "41",
        "45",
        "52",
        "67",
      ],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#ECC200",
        gradient: ["#FFFFFF", "#ECC200", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        playButtonColor: "#ECC200",
        playButtonBorder: "#000",
        ballTextColor: "#101820",
        lastBallTextColor: "#101820",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
  ];
}
