import { GameData } from "@/types/GameData";
import MegaMillionsLogo from "@/assets/logos/ny/megamillions.svg";
import PowerballLogo from "@/assets/logos/ny/powerball.svg";
import Cash4LifeLogo from "@/assets/logos/ny/cash4life.svg";
import NYLottoLogo from "@/assets/logos/ny/nylotto.svg";
import Take5MiddayLogo from "@/assets/logos/ny/take5midday.svg";
import Take5EveningLogo from "@/assets/logos/ny/take5evening.svg";
import Win4MiddayLogo from "@/assets/logos/ny/win4midday.svg";
import Win4EveningLogo from "@/assets/logos/ny/win4evening.svg";
import NumbersMiddayLogo from "@/assets/logos/ny/numbersmidday.svg";
import NumbersEveningLogo from "@/assets/logos/ny/numbersevening.svg";
import Pick10Logo from "@/assets/logos/ny/pick10.svg";

export async function fetchNewYorkGames(): Promise<GameData[]> {
  return [
    // Mega Millions
    {
      id: "megamillions_ny",
      name: "Mega Millions",
      slug: "megamillions",
      logo: MegaMillionsLogo,
      jackpot: "$143 Million",
      cashValue: "$66.8 Million",
      drawTime: "23:00:00",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "22", "33", "44", "55", "16"],
      bonusNumber: "16",
      powerPlay: "3x",
      result: "No Jackpot Winners    3 Match 5 Winner    NY",
      config_ui: {
        borderColor: "#0E4CA1",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#0E4CA1", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FFD700", "#B8860B"],
        lastBallTextColor: "#fff",
        playButtonColor: "#0E4CA1",
        playButtonBorder: "#EE3E33",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Powerball
    {
      id: "powerball_ny",
      name: "Powerball",
      slug: "powerball",
      logo: PowerballLogo,
      jackpot: "$95 Million",
      cashValue: "$45.7 Million",
      drawTime: "23:00:00",
      drawDate: "Wed, May 29, 2025",
      numbers: ["05", "09", "22", "34", "51", "10"],
      bonusNumber: "10",
      powerPlay: "2x",
      result: "No Jackpot Winners    3 Match 5 Winner    NY",
      config_ui: {
        borderColor: "#C7102E",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#C7102E", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FF6666", "#B1001C"],
        lastBallTextColor: "#fff",
        playButtonColor: "#C7102E",
        playButtonBorder: "#0E4CA1",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Cash4Life
    {
      id: "cash4life_ny",
      name: "Cash 4 Life",
      slug: "cash4life",
      logo: Cash4LifeLogo,
      jackpot: "$7 Million",
      cashValue: "$4.5 Million",
      drawTime: "21:00:00",
      drawDate: "Wed, May 29, 2025",
      numbers: ["05", "12", "21", "33", "37", "04"],
      bonusNumber: "04",
      powerPlay: "",
      result: "No Jackpot Winners    3 Match 5 Winner    NY",
      config_ui: {
        borderColor: "#009872",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#009872", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#F4FF82", "#7FA837"],
        lastBallTextColor: "#fff",
        playButtonColor: "#009872",
        playButtonBorder: "#5AC27C",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // NY Lotto
    {
      id: "nylotto_ny",
      name: "NY Lotto",
      slug: "nylotto",
      logo: NYLottoLogo,
      jackpot: "$12.3 Million",
      cashValue: "$7.5 Million",
      drawTime: "20:00:00",
      drawDate: "Wed, May 29, 2025",
      numbers: ["11", "19", "24", "38", "43", "48", "57"],
      bonusNumber: "03",
      powerPlay: "",
      result: "No Jackpot Winners    3 Match 5 Winner    NY",
      config_ui: {
        borderColor: "#D31245",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#D31245", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#F53C6D", "#A4143A"],
        lastBallTextColor: "#fff",
        playButtonColor: "#D31245",
        playButtonBorder: "#005596",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Take 5 Midday
    {
      id: "take5_midday_ny",
      name: "Take 5 Midday",
      slug: "take5_midday",
      logo: Take5MiddayLogo,
      jackpot: "$20,000",
      cashValue: "$20,000",
      drawTime: "14:30:00",
      drawDate: "Wed, May 29, 2025",
      numbers: ["02", "08", "13", "19", "24"],
      bonusNumber: "",
      powerPlay: "",
      result: "MIDDAY    5 Match Straight    NY",
      config_ui: {
        borderColor: "#CA3092",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#CA3092", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallTextColor: "#101820",
        playButtonColor: "#00928F",
        playButtonBorder: "#CA3092",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Take 5 Evening
    {
      id: "take5_evening_ny",
      name: "Take 5 Evening",
      slug: "take5_evening",
      logo: Take5EveningLogo,
      jackpot: "$20,000",
      cashValue: "$20,000",
      drawTime: "22:30:00",
      drawDate: "Wed, May 29, 2025",
      numbers: ["06", "15", "23", "25", "29"],
      bonusNumber: "",
      powerPlay: "",
      result: "EVENING    5 Match Straight    NY",
      config_ui: {
        borderColor: "#CA3092",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#CA3092", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallTextColor: "#101820",
        playButtonColor: "#00928F",
        playButtonBorder: "#CA3092",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Win 4 Midday
    {
      id: "win4_midday_ny",
      name: "Win 4 Midday",
      slug: "win4_midday",
      logo: Win4MiddayLogo,
      jackpot: "$5,000",
      cashValue: "$5,000",
      drawTime: "14:30:00",
      drawDate: "Wed, May 29, 2025",
      numbers: ["0", "7", "8", "0"],
      bonusNumber: "",
      powerPlay: "",
      result: "MIDDAY    5 Match Straight    NY",
      config_ui: {
        borderColor: "#7E0C6E",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#7E0C6E", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallTextColor: "#101820",
        playButtonColor: "#7E0C6E",
        playButtonBorder: "#7E0C6E",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Win 4 Evening
    {
      id: "win4_evening_ny",
      name: "Win 4 Evening",
      slug: "win4_evening",
      logo: Win4EveningLogo,
      jackpot: "$5,000",
      cashValue: "$5,000",
      drawTime: "22:30:00",
      drawDate: "Wed, May 29, 2025",
      numbers: ["04", "07", "12", "15"],
      bonusNumber: "",
      powerPlay: "",
      result: "EVENING    5 Match Straight    NY",
      config_ui: {
        borderColor: "#7E0C6E",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#7E0C6E", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallTextColor: "#101820",
        playButtonColor: "#7E0C6E",
        playButtonBorder: "#7E0C6E",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Numbers Midday
    {
      id: "numbers_midday_ny",
      name: "Numbers Midday",
      slug: "numbers_midday",
      logo: NumbersMiddayLogo,
      jackpot: "$500",
      cashValue: "$500",
      drawTime: "14:30:00",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "05", "09"],
      bonusNumber: "",
      powerPlay: "",
      result: "MIDDAY    5 Match Straight    NY",
      config_ui: {
        borderColor: "#2E73B5",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#2E73B5", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallTextColor: "#101820",
        playButtonColor: "#2E73B5",
        playButtonBorder: "#2E73B5",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Numbers Evening
    {
      id: "numbers_evening_ny",
      name: "Numbers Evening",
      slug: "numbers_evening",
      logo: NumbersEveningLogo,
      jackpot: "$500",
      cashValue: "$500",
      drawTime: "22:30:00",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "07", "09"],
      bonusNumber: "",
      powerPlay: "",
      result: "EVENING    5 Match Straight    NY",
      config_ui: {
        borderColor: "#2E73B5",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#2E73B5", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallTextColor: "#101820",
        playButtonColor: "#2E73B5",
        playButtonBorder: "#2E73B5",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Pick 10
    {
      id: "pick10_ny",
      name: "Pick 10",
      slug: "pick10",
      logo: Pick10Logo,
      jackpot: "$500,000",
      cashValue: "$500,000",
      drawTime: "12:30:00",
      drawDate: "Wed, May 29, 2025",
      numbers: [
        "02",
        "08",
        "17",
        "22",
        "30",
        "35",
        "41",
        "45",
        "52",
        "67",
        "04",
        "16",
        "18",
        "25",
        "33",
        "40",
        "44",
        "54",
        "55",
        "60",
      ],
      bonusNumber: "",
      powerPlay: "",
      result: "5 Jackpot Winners - NY",
      config_ui: {
        borderColor: "#ECC200",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#ECC200", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallTextColor: "#101820",
        playButtonColor: "#ECC200",
        playButtonBorder: "#000",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
  ];
}
