// app/(main)/generator/ny/gamesNormalConfig.ts

import MegaMillionsLogo from "@/assets/images/ny_game_logo/megamillions.svg";
import PowerballLogo from "@/assets/images/ny_game_logo/powerball.svg";
import Cash4LifeLogo from "@/assets/images/ny_game_logo/cash4life.svg";
import NYLottoLogo from "@/assets/images/ny_game_logo/nylotto.svg";
import Take5Logo from "@/assets/images/ny_game_logo/take5_midday.svg";
import Pick10Logo from "@/assets/images/ny_game_logo/pick10.svg";

export const normalGamesConfig = [
  {
    id: "megamillions_ny",
    name: "Mega Millions",
    type: "normal",
    logo: MegaMillionsLogo,
    headerColor: "#0E4CA1",
    mainGrid: {
      title: "Pick 5 Main Numbers",
      total: 70,
      pick: 5,
      color: "#fff",
      textColor: "#0E4CA1",
      selectedColor: "#0E4CA1",
      selectedTextColor: "#fff",
      selectedBorderColor: "#0E4CA1",
      pickedLabelColor: "#0E4CA1",
      pickedValueColor: "#fff",
      pickedBgColor: "#0E4CA1",
      pickedBorderColor: "#0E4CA1",
      linesLabelColor: "#333",
      linesValueColor: "#0E4CA1",
      linesBgColor: "#fff",
      linesBorderColor: "#0E4CA1",
      quickPickBgColor: "#0E4CA1",
      quickPickTextColor: "#fff",
      quickPickIconColor: "#FFD700",
      pickYourNumbersColor: "#333",
      gridBorderColor: "#e3e3e3",
    },
    extraGrid: {
      title: "Pick Mega Ball",
      total: 25,
      pick: 1,
      color: "#fff",
      textColor: "#FFB500",
      selectedColor: "#FFB500",
      selectedTextColor: "#fff",
      selectedBorderColor: "#FFB500",
      pickLabelColor: "#FFB500",
      gridBorderColor: "#e3e3e3",
    },
    resultsRoute: "/generator/ny/numbersgenerated",
  },
  {
    id: "powerball_ny",
    name: "Powerball",
    type: "normal",
    logo: PowerballLogo,
    headerColor: "#C7102E",
    mainGrid: {
      title: "Pick 5 Main Numbers",
      total: 69,
      pick: 5,
      color: "#fff",
      textColor: "#000",
      selectedColor: "#000",
      selectedTextColor: "#fff",
      selectedBorderColor: "#000",
      pickedLabelColor: "#222",
      pickedValueColor: "#fff",
      pickedBgColor: "#000",
      pickedBorderColor: "#000",
      linesLabelColor: "#333",
      linesValueColor: "#C7102E",
      linesBgColor: "#fff",
      linesBorderColor: "#C7102E",
      quickPickBgColor: "#000",
      quickPickTextColor: "#fff",
      quickPickIconColor: "#FFD700",
      pickYourNumbersColor: "#333",
      gridBorderColor: "#e3e3e3",
    },
    extraGrid: {
      title: "Pick Powerball",
      total: 26,
      pick: 1,
      color: "#fff",
      textColor: "#000",
      selectedColor: "#C7102E",
      selectedTextColor: "#fff",
      selectedBorderColor: "#C7102E",
      pickLabelColor: "#C7102E",
      gridBorderColor: "#e3e3e3",
    },
    resultsRoute: "/generator/ny/numbersgenerated",
  },
  {
    id: "cash4life_ny",
    name: "Cash 4 Life",
    type: "normal",
    logo: Cash4LifeLogo,
    headerColor: "#2D7F67",
    mainGrid: {
      title: "Pick 5 Main Numbers",
      total: 60,
      pick: 5,
      color: "#2D7F67",
      textColor: "#fff",
      selectedColor: "#2D7F67",
      selectedTextColor: "#000",
      selectedBorderColor: "#2D7F67",
      pickedLabelColor: "#2D7F67",
      pickedValueColor: "#FFD700",
      pickedBgColor: "#2D7F67",
      pickedBorderColor: "#2D7F67",
      linesLabelColor: "#333",
      linesValueColor: "#2D7F67",
      linesBgColor: "#fff",
      linesBorderColor: "#2D7F67",
      quickPickBgColor: "#2D7F67",
      quickPickTextColor: "#fff",
      quickPickIconColor: "#FFD700",
      pickYourNumbersColor: "#333",
      gridBorderColor: "#e3e3e3",
    },
    extraGrid: {
      title: "Pick Cash Ball",
      total: 4,
      pick: 1,
      color: "#fff",
      textColor: "#2D7F67",
      selectedColor: "#2D7F67",
      selectedTextColor: "#fff",
      selectedBorderColor: "#2D7F67",
      pickLabelColor: "#2D7F67",
      gridBorderColor: "#e3e3e3",
    },
    resultsRoute: "/generator/ny/numbersgenerated",
  },
  {
    id: "nylotto_ny",
    name: "NY Lotto",
    type: "normal",
    logo: NYLottoLogo,
    headerColor: "#003C8D",
    mainGrid: {
      title: "Pick 6 Main Numbers",
      total: 59,
      pick: 6,
      color: "#fff",
      textColor: "#003C8D",
      selectedColor: "#003C8D",
      selectedTextColor: "#fff",
      selectedBorderColor: "#003C8D",
      pickedLabelColor: "#003C8D",
      pickedValueColor: "#fff",
      pickedBgColor: "#003C8D",
      pickedBorderColor: "#003C8D",
      linesLabelColor: "#333",
      linesValueColor: "#003C8D",
      linesBgColor: "#fff",
      linesBorderColor: "#003C8D",
      quickPickBgColor: "#003C8D",
      quickPickTextColor: "#fff",
      quickPickIconColor: "#FFD700",
      pickYourNumbersColor: "#333",
      gridBorderColor: "#e3e3e3",
    },
    extraGrid: null,
    resultsRoute: "/generator/ny/numbersgenerated",
  },
  {
    id: "take5_midday_ny",
    name: "Take 5 Midday",
    type: "normal",
    logo: Take5Logo,
    headerColor: "#43B02A",
    mainGrid: {
      title: "Pick 5 Main Numbers",
      total: 39,
      pick: 5,
      color: "#fff",
      textColor: "#43B02A",
      selectedColor: "#43B02A",
      selectedTextColor: "#fff",
      selectedBorderColor: "#43B02A",
      pickedLabelColor: "#43B02A",
      pickedValueColor: "#fff",
      pickedBgColor: "#43B02A",
      pickedBorderColor: "#43B02A",
      linesLabelColor: "#333",
      linesValueColor: "#43B02A",
      linesBgColor: "#fff",
      linesBorderColor: "#43B02A",
      quickPickBgColor: "#43B02A",
      quickPickTextColor: "#fff",
      quickPickIconColor: "#FFD700",
      pickYourNumbersColor: "#333",
      gridBorderColor: "#e3e3e3",
    },
    extraGrid: null,
    resultsRoute: "/generator/ny/numbersgenerated",
  },
  {
    id: "take5_evening_ny",
    name: "Take 5 Evening",
    type: "normal",
    logo: Take5Logo,
    headerColor: "#43B02A",
    mainGrid: {
      title: "Pick 5 Main Numbers",
      total: 39,
      pick: 5,
      color: "#fff",
      textColor: "#43B02A",
      selectedColor: "#43B02A",
      selectedTextColor: "#fff",
      selectedBorderColor: "#43B02A",
      pickedLabelColor: "#43B02A",
      pickedValueColor: "#fff",
      pickedBgColor: "#43B02A",
      pickedBorderColor: "#43B02A",
      linesLabelColor: "#333",
      linesValueColor: "#43B02A",
      linesBgColor: "#fff",
      linesBorderColor: "#43B02A",
      quickPickBgColor: "#43B02A",
      quickPickTextColor: "#fff",
      quickPickIconColor: "#FFD700",
      pickYourNumbersColor: "#333",
      gridBorderColor: "#e3e3e3",
    },
    extraGrid: null,
    resultsRoute: "/generator/ny/numbersgenerated",
  },
  {
    id: "pick10",
    name: "Pick 10",
    type: "normal",
    logo: Pick10Logo,
    headerColor: "#4F2683",
    mainGrid: {
      title: "Pick 10 Numbers",
      total: 80,
      pick: 10,
      color: "#fff",
      textColor: "#4F2683",
      selectedColor: "#4F2683",
      selectedTextColor: "#fff",
      selectedBorderColor: "#4F2683",
      pickedLabelColor: "#4F2683",
      pickedValueColor: "#fff",
      pickedBgColor: "#4F2683",
      pickedBorderColor: "#4F2683",
      linesLabelColor: "#333",
      linesValueColor: "#4F2683",
      linesBgColor: "#fff",
      linesBorderColor: "#4F2683",
      quickPickBgColor: "#4F2683",
      quickPickTextColor: "#fff",
      quickPickIconColor: "#FFD700",
      pickYourNumbersColor: "#333",
      gridBorderColor: "#e3e3e3",
    },
    extraGrid: null,
    resultsRoute: "/generator/ny/numbersgenerated",
  },
];
