import { GameData } from "@/types/GameData";
import SuperLottoLogo from "@/assets/logos/CA/superlotto.svg";
import PowerballLogo from "@/assets/logos/CA/powerball.svg";
import MegaMillionsLogo from "@/assets/logos/CA/megamillions.svg";
import Fantasy5Logo from "@/assets/logos/CA/fantasy5.svg";
import Daily3MiddayLogo from "@/assets/logos/CA/daily3midday.svg";
import Daily4Logo from "@/assets/logos/CA/daily4.svg";
import DailyDerbyLogo from "@/assets/logos/CA/dailyderby.svg";

export async function fetchCaliforniaGames(): Promise<GameData[]> {
  return [
    {
      id: "ca_superlotto",
      name: "SuperLotto Plus",
      slug: "superlotto",
      logo: SuperLottoLogo,
      jackpot: "$45 Million",
      cashValue: "$27 Million",
      drawTime: "Wed & Sat 7:45 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["05", "11", "26", "34", "39", "18"],
      bonusNumber: "",
      result: "",
      powerPlay: "",
      config_ui: {
        borderColor: "#0057B8",
        borderWidth: 3,
        borderRadius: 28,
        background: "#F2F7FF",
        gradient: ["#F2F7FF", "#0057B8", "#F2F7FF"],
        ballGradient: ["#FFF", "#B3D4FC"],
        lastBallGradient: ["#FFF", "#0057B8"],
        ballTextColor: "#0057B8",
        lastBallTextColor: "#fff",
        playButtonColor: "#0057B8",
        playButtonBorder: "#0057B8",
      },
    },
    {
      id: "ca_powerball",
      name: "Powerball",
      slug: "powerball",
      logo: PowerballLogo,
      jackpot: "$143 Million",
      cashValue: "$66.8 Million",
      drawTime: "Wed & Sat 10:59 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["11", "17", "23", "42", "58", "14"],
      bonusNumber: "",
      result: "",
      powerPlay: "3x",
      config_ui: {
        borderColor: "#C7102E",
        borderWidth: 3,
        borderRadius: 28,
        background: "#FFF",
        gradient: ["#FFFFFF", "#C7102E", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FF6666", "#B1001C"],
        ballTextColor: "#C7102E",
        lastBallTextColor: "#fff",
        playButtonColor: "#C7102E",
        playButtonBorder: "#C7102E",
      },
    },
    {
      id: "ca_megamillions",
      name: "Mega Millions",
      slug: "megamillions",
      logo: MegaMillionsLogo,
      jackpot: "$143 Million",
      cashValue: "$66.8 Million",
      drawTime: "Tue & Fri 11:00 PM",
      drawDate: "Tue, May 28, 2025",
      numbers: ["19", "23", "39", "45", "49", "18"],
      bonusNumber: "",
      result: "",
      powerPlay: "",
      config_ui: {
        borderColor: "#0E4CA1",
        borderWidth: 3,
        borderRadius: 28,
        background: "#FFF",
        gradient: ["#FFFFFF", "#0E4CA1", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#1C91FF", "#011F3C"],
        ballTextColor: "#0E4CA1",
        lastBallTextColor: "#fff",
        playButtonColor: "#0E4CA1",
        playButtonBorder: "#0E4CA1",
      },
    },
    {
      id: "ca_fantasy5",
      name: "Fantasy 5",
      slug: "fantasy5",
      logo: Fantasy5Logo,
      jackpot: "$75,000",
      cashValue: "$75,000",
      drawTime: "Daily 6:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["05", "12", "21", "33", "37"],
      bonusNumber: "",
      result: "",
      powerPlay: "",
      config_ui: {
        borderColor: "#8FBC3F",
        borderWidth: 3,
        borderRadius: 28,
        background: "#F7FFF3",
        gradient: ["#F7FFF3", "#8FBC3F", "#F7FFF3"],
        ballGradient: ["#FFF", "#B7EAB7"],
        lastBallGradient: ["#FFF", "#8FBC3F"],
        ballTextColor: "#8FBC3F",
        lastBallTextColor: "#fff",
        playButtonColor: "#8FBC3F",
        playButtonBorder: "#8FBC3F",
      },
    },
    {
      id: "ca_daily3",
      name: "Daily 3",
      slug: "daily3",
      logo: Daily3MiddayLogo,
      jackpot: "$500",
      cashValue: "$500",
      drawTime: "Daily 1:00 & 6:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["6", "5", "8"],
      bonusNumber: "",
      result: "",
      powerPlay: "",
      config_ui: {
        borderColor: "#FF9100",
        borderWidth: 3,
        borderRadius: 28,
        background: "#FFF8E1",
        gradient: ["#FFF8E1", "#FF9100", "#FFF8E1"],
        ballGradient: ["#FFF", "#FFD180"],
        lastBallGradient: ["#FFF", "#FF9100"],
        ballTextColor: "#FF9100",
        lastBallTextColor: "#fff",
        playButtonColor: "#FF9100",
        playButtonBorder: "#FF9100",
      },
    },
    {
      id: "ca_daily4",
      name: "Daily 4",
      slug: "daily4",
      logo: Daily4Logo,
      jackpot: "$5,000",
      cashValue: "$5,000",
      drawTime: "Daily 6:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["7", "2", "3", "6"],
      bonusNumber: "",
      result: "",
      powerPlay: "",
      config_ui: {
        borderColor: "#3949AB",
        borderWidth: 3,
        borderRadius: 28,
        background: "#F3F3FF",
        gradient: ["#F3F3FF", "#3949AB", "#F3F3FF"],
        ballGradient: ["#FFF", "#7986CB"],
        lastBallGradient: ["#FFF", "#3949AB"],
        ballTextColor: "#3949AB",
        lastBallTextColor: "#fff",
        playButtonColor: "#3949AB",
        playButtonBorder: "#3949AB",
      },
    },
    {
      id: "ca_dailyderby",
      name: "Daily Derby",
      slug: "dailyderby",
      logo: DailyDerbyLogo,
      jackpot: "$200,000",
      cashValue: "$200,000",
      drawTime: "Daily 6:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["H3", "H7", "H9", "Time: 1:45.07"],
      bonusNumber: "",
      result: "",
      powerPlay: "",
      config_ui: {
        borderColor: "#CB7200",
        borderWidth: 3,
        borderRadius: 28,
        background: "#FFF7EB",
        gradient: ["#FFF7EB", "#CB7200", "#FFF7EB"],
        ballGradient: ["#FFF", "#FFD54F"],
        lastBallGradient: ["#FFF", "#CB7200"],
        ballTextColor: "#CB7200",
        lastBallTextColor: "#fff",
        playButtonColor: "#CB7200",
        playButtonBorder: "#CB7200",
      },
    },
  ];
}
