import { GameData } from "@/types/GameData";

// IMPORTS DOS LOGOS (ajuste os caminhos conforme a pasta do seu projeto!)
import PowerballLogo from "@/assets/logos/CA/powerball.svg";
import MegaMillionsLogo from "@/assets/logos/CA/megamillions.svg";
import SuperLottoLogo from "@/assets/logos/CA/superlotto.svg";
import Fantasy5Logo from "@/assets/logos/CA/fantasy5.svg";
import Daily3MiddayLogo from "@/assets/logos/CA/daily3midday.svg";
import Daily3EveningLogo from "@/assets/logos/CA/daily3evening.svg";
import Daily4Logo from "@/assets/logos/CA/daily4.svg";
import DailyDerbyLogo from "@/assets/logos/CA/dailyderby.svg";

// Exporte a função com o nome correto!
export async function fetchCaliforniaGames(): Promise<GameData[]> {
  return [
    // Powerball (igual para todos os estados)
    {
      id: "powerball_ca",
      name: "Powerball",
      slug: "powerball",
      logo: PowerballLogo,
      jackpot: "$95 Million",
      cashValue: "$45.7 Million",
      drawTime: "Mon, Wed, Sat 10:59 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["05", "09", "22", "34", "51", "10"],
      bonusNumber: "10",
      powerPlay: "2x",
      result: "No Jackpot Winner | 1 Match 5 Winner | CA",
      config_ui: {
        borderColor: "#C7102E",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#C7102E", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FF6666", "#B1001C"],
        lastBallTextColor: "#fff",
        playButtonColor: "#C7102E",
        playButtonBorder: "#0E4CA1",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    // Mega Millions (igual para todos os estados)
    {
      id: "megamillions_ca",
      name: "Mega Millions",
      slug: "megamillions",
      logo: MegaMillionsLogo,
      jackpot: "$143 Million",
      cashValue: "$66.8 Million",
      drawTime: "Tue & Fri 11:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "22", "33", "44", "55", "16"],
      bonusNumber: "16",
      powerPlay: "3x",
      result: "No Jackpot Winners | 3 Match 5 Winner | CA",
      config_ui: {
        borderColor: "#0E4CA1",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#0E4CA1", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FFD700", "#B8860B"],
        lastBallTextColor: "#fff",
        playButtonColor: "#0E4CA1",
        playButtonBorder: "#EE3E33",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    // SuperLotto Plus
    {
      id: "superlotto_ca",
      name: "SuperLotto Plus",
      slug: "superlotto",
      logo: SuperLottoLogo,
      jackpot: "$52 Million",
      cashValue: "$33 Million",
      drawTime: "Wed & Sat 7:57 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["11", "19", "22", "31", "44", "13"],
      bonusNumber: "13",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#01BBF1", // Azul claro do logo
        borderWidth: 4,
        borderRadius: 22,
        background: "#F4F9FF",
        gradient: ["#F4F9FF", "#01BBF1", "#F4F9FF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#000",
        lastBallGradient: ["#DCAD09", "#AB8B00"],
        lastBallTextColor: "#000",
        playButtonColor: "#01BBF1",
        playButtonBorder: "#01BBF1",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    // Fantasy 5
    {
      id: "fantasy5_ca",
      name: "Fantasy 5",
      slug: "fantasy5",
      logo: Fantasy5Logo,
      jackpot: "$81,000",
      cashValue: "$81,000",
      drawTime: "Daily 6:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["03", "09", "14", "23", "35"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#01BBF1", // Azul claro do logo
        borderWidth: 4,
        borderRadius: 22,
        background: "#F4F9FF",
        gradient: ["#F4F9FF", "#01BBF1", "#F4F9FF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#000",
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallTextColor: "#000",
        playButtonColor: "#01BBF1",
        playButtonBorder: "#01BBF1",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    // Daily 3 Midday
    {
      id: "daily3midday_ca",
      name: "Daily 3 Midday",
      slug: "daily3midday",
      logo: Daily3MiddayLogo,
      jackpot: "$500",
      cashValue: "$500",
      drawTime: "Daily 1:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["04", "07", "09"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#01BBF1", // Azul claro do logo
        borderWidth: 4,
        borderRadius: 22,
        background: "#F4F9FF",
        gradient: ["#F4F9FF", "#01BBF1", "#F4F9FF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#000",
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallTextColor: "#000",
        playButtonColor: "#01BBF1",
        playButtonBorder: "#01BBF1",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    // Daily 3 Evening
    {
      id: "daily3evening_ca",
      name: "Daily 3 Evening",
      slug: "daily3evening",
      logo: Daily3EveningLogo,
      jackpot: "$500",
      cashValue: "$500",
      drawTime: "Daily 6:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "08", "09"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#01BBF1", // Azul claro do logo
        borderWidth: 4,
        borderRadius: 22,
        background: "#F4F9FF",
        gradient: ["#F4F9FF", "#01BBF1", "#F4F9FF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#000",
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallTextColor: "#000",
        playButtonColor: "#01BBF1",
        playButtonBorder: "#01BBF1",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    // Daily 4
    {
      id: "daily4_ca",
      name: "Daily 4",
      slug: "daily4",
      logo: Daily4Logo,
      jackpot: "$5,000",
      cashValue: "$5,000",
      drawTime: "Daily 6:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "05", "09", "11"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#01BBF1", // Azul claro do logo
        borderWidth: 4,
        borderRadius: 22,
        background: "#F4F9FF",
        gradient: ["#F4F9FF", "#01BBF1", "#F4F9FF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#000",
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallTextColor: "#000",
        playButtonColor: "#01BBF1",
        playButtonBorder: "#01BBF1",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    // Daily Derby
    {
      id: "dailyderby_ca",
      name: "Daily Derby",
      slug: "dailyderby",
      logo: DailyDerbyLogo,
      jackpot: "$45,000",
      cashValue: "$45,000",
      drawTime: "Daily 6:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["07", "03", "12"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#01BBF1", // Azul claro do logo
        borderWidth: 4,
        borderRadius: 22,
        background: "#F4F9FF",
        gradient: ["#F4F9FF", "#01BBF1", "#F4F9FF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#000",
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallTextColor: "#000",
        playButtonColor: "#01BBF1",
        playButtonBorder: "#01BBF1",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
  ];
}
