// states/AR/games.ts
import { GameData } from "@/types/GameData";
import PowerballLogo from "@/assets/logos/AR/powerball.svg";
import MegaMillionsLogo from "@/assets/logos/AR/megamillions.svg";
import Cash3MiddayLogo from "@/assets/logos/AR/cash3midday.svg";
import Cash3EveningLogo from "@/assets/logos/AR/cash3evening.svg";
import Cash4MiddayLogo from "@/assets/logos/AR/cash4midday.svg";
import Cash4EveningLogo from "@/assets/logos/AR/cash4evening.svg";
import LottoLogo from "@/assets/logos/AR/lotto.svg";
import LuckyForLifeLogo from "@/assets/logos/AR/luckyforlife.svg";
import NaturalStateJackpotLogo from "@/assets/logos/AR/naturalstatejackpot.svg";

// Todas as bolas seguem o padrão nacional, NÃO modifique as bolas!
// As cores dos cards (bordas, fundo, botões) refletem as cores principais do logo de cada jogo.

export async function fetchArkansasGames(): Promise<GameData[]> {
  return [
    {
      id: "powerball_ar",
      name: "Powerball",
      slug: "powerball",
      logo: PowerballLogo,
      jackpot: "$95 Million",
      cashValue: "$45.7 Million",
      drawTime: "Mon, Wed, Sat 10:59 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["05", "09", "22", "34", "51", "10"],
      bonusNumber: "10",
      powerPlay: "2x",
      result:
        "No Jackpot Winners                                                                                             3 Match 5 Winner                                                          AR",
      config_ui: {
        borderColor: "#C7102E",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#C7102E", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FF6666", "#B1001C"],
        lastBallTextColor: "#fff",
        playButtonColor: "#C7102E",
        playButtonBorder: "#0E4CA1",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "megamillions_ar",
      name: "Mega Millions",
      slug: "megamillions",
      logo: MegaMillionsLogo,
      jackpot: "$143 Million",
      cashValue: "$66.8 Million",
      drawTime: "Tue & Fri 11:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "22", "33", "44", "55", "16"],
      bonusNumber: "16",
      powerPlay: "3x",
      result:
        "No Jackpot Winners                                                                                             3 Match 5 Winner                                                          AR",
      config_ui: {
        borderColor: "#0E4CA1",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#0E4CA1", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FFD700", "#DCAD09"],
        lastBallTextColor: "#fff",
        playButtonColor: "#0E4CA1",
        playButtonBorder: "#EE3E33",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "lotto_ar",
      name: "Lotto",
      slug: "lotto",
      logo: LottoLogo,
      jackpot: "$1.7 Million",
      cashValue: "$1.1 Million",
      drawTime: "Wed & Sat 9:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["09", "19", "28", "33", "37", "39", "42"],
      bonusNumber: "",
      powerPlay: "",
      result:
        "No Jackpot Winners                                                                                             3 Match 5 Winner                                                          AR",
      config_ui: {
        borderColor: "#1F5EC6",
        gradient: ["#FFFFFF", "#1F5EC6", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FF6666", "#B1001C"],
        playButtonColor: "#1F5EC6",
        playButtonBorder: "#01299B",
        ballTextColor: "#101820",
        lastBallTextColor: "#FFF",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "naturalstatejackpot_ar",
      name: "Natural State Jackpot",
      slug: "naturalstatejackpot",
      logo: NaturalStateJackpotLogo,
      jackpot: "$150,000",
      cashValue: "$150,000",
      drawTime: "Mon-Sat 8:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["06", "12", "17", "25", "33"],
      bonusNumber: "",
      powerPlay: "",
      result:
        "No Jackpot Winners                                                                                             3 Match 5 Winner                                                          AR",
      config_ui: {
        borderColor: "#005CB9",
        gradient: ["#FFFFFF", "#005CB9", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        playButtonColor: "#E31D1A",
        playButtonBorder: "#005CB9",
        ballTextColor: "#101820",
        lastBallTextColor: "#101820",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "luckyforlife_ar",
      name: "Lucky for Life",
      slug: "luckyforlife",
      logo: LuckyForLifeLogo,
      jackpot: "$1,000 a Day for Life",
      cashValue: "$1,000",
      drawTime: "Daily 9:38 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "02", "03", "04", "05", "18"],
      bonusNumber: "18",
      powerPlay: "",
      result:
        "No Jackpot Winners                                                                                             3 Match 5 Winner                                                          AR",
      config_ui: {
        borderColor: "#007934",
        gradient: ["#FFFFFF", "#007934", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#007934", "#2B5134"],
        playButtonColor: "#2B5134",
        playButtonBorder: "#007934",
        ballTextColor: "#101820",
        lastBallTextColor: "#fff",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "cash4midday_ar",
      name: "Cash 4 Midday",
      slug: "cash4midday",
      logo: Cash4MiddayLogo,
      jackpot: "$5,000",
      cashValue: "$5,000",
      drawTime: "Mon-Sun 12:59 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["02", "03", "06", "09"],
      bonusNumber: "",
      powerPlay: "",
      result:
        "MIDDAY                                                                                             5 Match Straight                                                        AR",

      config_ui: {
        borderColor: "#BAD644",
        gradient: ["#FFFFFF", "#BAD644", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        playButtonColor: "#7EBF51",
        playButtonBorder: "#BAD644",
        ballTextColor: "#101820",
        lastBallTextColor: "#101820",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "cash4evening_ar",
      name: "Cash 4 Evening",
      slug: "cash4evening",
      logo: Cash4EveningLogo,
      jackpot: "$5,000",
      cashValue: "$5,000",
      drawTime: "Mon-Sun 6:59 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "04", "07", "08"],
      bonusNumber: "",
      powerPlay: "",
      result:
        "EVENING                                                                                             5 Match Straight                                                        AR",

      config_ui: {
        borderColor: "#BAD644",
        gradient: ["#FFFFFF", "#BAD644", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        playButtonColor: "#7EBF51",
        playButtonBorder: "#BAD644",
        ballTextColor: "#101820",
        lastBallTextColor: "#101820",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "cash3midday_ar",
      name: "Cash 3 Midday",
      slug: "cash3midday",
      logo: Cash3MiddayLogo,
      jackpot: "$500",
      cashValue: "$500",
      drawTime: "Mon-Sun 12:59 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["03", "04", "08"],
      bonusNumber: "",
      powerPlay: "",
      result:
        "MIDDAY                                                                                             5 Match Straight                                                        AR",

      config_ui: {
        borderColor: "#00ADE5",
        gradient: ["#FFFFFF", "#00ADE5", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        playButtonColor: "#79D6F7",
        playButtonBorder: "#00ADE5",
        ballTextColor: "#101820",
        lastBallTextColor: "#101820",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "cash3evening_ar",
      name: "Cash 3 Evening",
      slug: "cash3evening",
      logo: Cash3EveningLogo,
      jackpot: "$500",
      cashValue: "$500",
      drawTime: "Mon-Sun 6:59 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "09", "06"],
      bonusNumber: "",
      powerPlay: "",
      result:
        "EVENING                                                                                             5 Match Straight                                                        AR",

      config_ui: {
        borderColor: "#00ADE5",
        gradient: ["#FFFFFF", "#00ADE5", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        playButtonColor: "#79D6F7",
        playButtonBorder: "#00ADE5",
        ballTextColor: "#101820",
        lastBallTextColor: "#101820",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
  ];
}
