import { GameData } from "@/types/GameData";
import NaturalStateJackpotLogo from "@/assets/logos/AR/naturalstatejackpot.svg";
import PowerballLogo from "@/assets/logos/AR/powerball.svg";
import MegaMillionsLogo from "@/assets/logos/AR/megamillions.svg";
import Cash3MiddayLogo from "@/assets/logos/AR/cash3midday.svg";
import Cash4MiddayLogo from "@/assets/logos/AR/cash4midday.svg";
import LuckyForLifeLogo from "@/assets/logos/AR/luckyforlife.svg";
import LottoLogo from "@/assets/logos/AR/lotto.svg";

export async function fetchArkansasGames(): Promise<GameData[]> {
  return [
    {
      id: "ar_naturalstatejackpot",
      name: "Natural State Jackpot",
      slug: "naturalstatejackpot",
      logo: NaturalStateJackpotLogo,
      jackpot: "$130,000",
      cashValue: "$130,000",
      drawTime: "Mon-Sat 8:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["04", "11", "22", "34", "38"],
      bonusNumber: "",
      result: "",
      powerPlay: "",
      config_ui: {
        borderColor: "#198754",
        borderWidth: 3,
        borderRadius: 28,
        background: "#FFF",
        gradient: ["#FFFFFF", "#198754", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#CCCCCC"],
        lastBallGradient: ["#D1FAE5", "#198754"],
        ballTextColor: "#198754",
        lastBallTextColor: "#fff",
        playButtonColor: "#198754",
        playButtonBorder: "#198754",
      },
    },
    {
      id: "ar_powerball",
      name: "Powerball",
      slug: "powerball",
      logo: PowerballLogo,
      jackpot: "$143 Million",
      cashValue: "$66.8 Million",
      drawTime: "Wed & Sat 10:59 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["11", "17", "23", "42", "58", "14"],
      bonusNumber: "",
      result: "",
      powerPlay: "3x",
      config_ui: {
        borderColor: "#C7102E",
        borderWidth: 3,
        borderRadius: 28,
        background: "#FFF",
        gradient: ["#FFFFFF", "#C7102E", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#FF6666", "#B1001C"],
        ballTextColor: "#C7102E",
        lastBallTextColor: "#fff",
        playButtonColor: "#C7102E",
        playButtonBorder: "#C7102E",
      },
    },
    {
      id: "ar_megamillions",
      name: "Mega Millions",
      slug: "megamillions",
      logo: MegaMillionsLogo,
      jackpot: "$143 Million",
      cashValue: "$66.8 Million",
      drawTime: "Tue & Fri 11:00 PM",
      drawDate: "Tue, May 28, 2025",
      numbers: ["19", "23", "39", "45", "49", "18"],
      bonusNumber: "",
      result: "",
      powerPlay: "",
      config_ui: {
        borderColor: "#0E4CA1",
        borderWidth: 3,
        borderRadius: 28,
        background: "#FFF",
        gradient: ["#FFFFFF", "#0E4CA1", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallGradient: ["#1C91FF", "#011F3C"],
        ballTextColor: "#0E4CA1",
        lastBallTextColor: "#fff",
        playButtonColor: "#0E4CA1",
        playButtonBorder: "#0E4CA1",
      },
    },
    {
      id: "ar_cash3",
      name: "Cash 3",
      slug: "cash3",
      logo: Cash3MiddayLogo,
      jackpot: "$500",
      cashValue: "$500",
      drawTime: "Mon-Sat 12:59 PM & 6:59 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["2", "3", "7"],
      bonusNumber: "",
      result: "",
      powerPlay: "",
      config_ui: {
        borderColor: "#FFC107",
        borderWidth: 3,
        borderRadius: 28,
        background: "#FFFDE7",
        gradient: ["#FFFDE7", "#FFC107", "#FFFDE7"],
        ballGradient: ["#FFF", "#FFD54F"],
        lastBallGradient: ["#FFF", "#FFA000"],
        ballTextColor: "#FFA000",
        lastBallTextColor: "#fff",
        playButtonColor: "#FFC107",
        playButtonBorder: "#FFA000",
      },
    },
    {
      id: "ar_cash4",
      name: "Cash 4",
      slug: "cash4",
      logo: Cash4MiddayLogo,
      jackpot: "$5,000",
      cashValue: "$5,000",
      drawTime: "Mon-Sat 12:59 PM & 6:59 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["6", "0", "9", "8"],
      bonusNumber: "",
      result: "",
      powerPlay: "",
      config_ui: {
        borderColor: "#6C63FF",
        borderWidth: 3,
        borderRadius: 28,
        background: "#F3F3FF",
        gradient: ["#F3F3FF", "#6C63FF", "#F3F3FF"],
        ballGradient: ["#FFF", "#AEB8FE"],
        lastBallGradient: ["#FFF", "#6C63FF"],
        ballTextColor: "#6C63FF",
        lastBallTextColor: "#fff",
        playButtonColor: "#6C63FF",
        playButtonBorder: "#6C63FF",
      },
    },
    {
      id: "ar_luckyforlife",
      name: "Lucky for Life",
      slug: "luckyforlife",
      logo: LuckyForLifeLogo,
      jackpot: "$1,000 a Day for Life",
      cashValue: "$7,000,000 (lump sum)",
      drawTime: "Daily 9:38 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["11", "18", "24", "34", "44", "7"],
      bonusNumber: "",
      result: "",
      powerPlay: "",
      config_ui: {
        borderColor: "#009E60",
        borderWidth: 3,
        borderRadius: 28,
        background: "#F0FFF4",
        gradient: ["#F0FFF4", "#009E60", "#F0FFF4"],
        ballGradient: ["#FFF", "#6FCF97"],
        lastBallGradient: ["#FFF", "#009E60"],
        ballTextColor: "#009E60",
        lastBallTextColor: "#fff",
        playButtonColor: "#009E60",
        playButtonBorder: "#009E60",
      },
    },
    {
      id: "ar_lotto",
      name: "LOTTO",
      slug: "lotto",
      logo: LottoLogo,
      jackpot: "$1,210,000",
      cashValue: "$1,210,000",
      drawTime: "Wed & Sat 9:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["03", "12", "25", "28", "37", "40"],
      bonusNumber: "",
      result: "",
      powerPlay: "",
      config_ui: {
        borderColor: "#9D6CFF",
        borderWidth: 3,
        borderRadius: 28,
        background: "#FCF6FF",
        gradient: ["#FCF6FF", "#9D6CFF", "#FCF6FF"],
        ballGradient: ["#FFF", "#D1C4E9"],
        lastBallGradient: ["#FFF", "#9D6CFF"],
        ballTextColor: "#9D6CFF",
        lastBallTextColor: "#fff",
        playButtonColor: "#9D6CFF",
        playButtonBorder: "#9D6CFF",
      },
    },
  ];
}
