// states/co/games.ts
import { GameData } from "@/types/GameData";

// LOGOS
import MegaMillionsLogo from "@/assets/logos/co/megamillions.svg";
import PowerballLogo from "@/assets/logos/co/powerball.svg";
import LuckyForLifeLogo from "@/assets/logos/co/luckyforlife.svg";
import Cash5Logo from "@/assets/logos/co/cash5.svg";
import LottoPlusLogo from "@/assets/logos/co/lottoplus.svg";
import Cash3MiddayLogo from "@/assets/logos/co/cash3midday.svg";
import Cash3EveningLogo from "@/assets/logos/co/cash3evening.svg";
import PowerballDoublePlayLogo from "@/assets/logos/co/powerballdouplepay.svg";

export async function fetchColoradoGames(): Promise<GameData[]> {
  return [
    {
      id: "megamillions_co",
      name: "Mega Millions",
      slug: "megamillions",
      logo: MegaMillionsLogo,
      jackpot: "$143 Million",
      cashValue: "$66.8 Million",
      drawTime: "Tue & Fri 11:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "22", "33", "44", "55", "16"],
      bonusNumber: "16",
      powerPlay: "3x",
      result: "No Jackpot Winners | 3 Match 5 Winner | NY",
      config_ui: {
        borderColor: "#0E4CA1",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#0E4CA1", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FFD700", "#B8860B"],
        lastBallTextColor: "#fff",
        playButtonColor: "#0E4CA1",
        playButtonBorder: "#EE3E33",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "powerball_co",
      name: "Powerball",
      slug: "powerball",
      logo: PowerballLogo,
      jackpot: "$95 Million",
      cashValue: "$45.7 Million",
      drawTime: "Mon, Wed, Sat 10:59 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["05", "09", "22", "34", "51", "10"],
      bonusNumber: "10",
      powerPlay: "2x",
      result: "No Jackpot Winner | 1 Match 5 Winner | CO",
      config_ui: {
        borderColor: "#C7102E",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#C7102E", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FF6666", "#B1001C"],
        lastBallTextColor: "#fff",
        playButtonColor: "#C7102E",
        playButtonBorder: "#0E4CA1",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "luckyforlife_co",
      name: "Lucky for Life",
      slug: "luckyforlife",
      logo: LuckyForLifeLogo,
      jackpot: "$1,000/Day for Life",
      cashValue: "$5,750,000",
      drawTime: "Daily 10:38 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["02", "15", "23", "31", "40", "06"],
      bonusNumber: "06",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#52AE30",
        borderWidth: 4,
        borderRadius: 22,
        background: "#F5FFF2",
        gradient: ["#E1FFD9", "#52AE30", "#F5FFF2"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#2A6520",
        lastBallGradient: ["#95E448", "#357A2C"],
        lastBallTextColor: "#fff",
        playButtonColor: "#52AE30",
        playButtonBorder: "#357A2C",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "cash5_co",
      name: "Cash 5",
      slug: "cash5",
      logo: Cash5Logo,
      jackpot: "$20,000",
      cashValue: "$20,000",
      drawTime: "Daily 7:35 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["07", "13", "19", "24", "32"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#0094D2",
        borderWidth: 4,
        borderRadius: 22,
        background: "#F2FAFF",
        gradient: ["#E0F6FF", "#0094D2", "#F2FAFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#005780",
        lastBallGradient: ["#0094D2", "#005780"],
        lastBallTextColor: "#fff",
        playButtonColor: "#0094D2",
        playButtonBorder: "#0074A8",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "lottoplus_co",
      name: "Lotto+",
      slug: "lottoplus",
      logo: LottoPlusLogo,
      jackpot: "$1.8 Million",
      cashValue: "$1,020,000",
      drawTime: "Wed & Sat 7:35 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["04", "11", "21", "35", "48", "52"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#A6328D",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF3FD",
        gradient: ["#F8E2FA", "#A6328D", "#FFF3FD"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#6C1856",
        lastBallGradient: ["#A6328D", "#F8E2FA"],
        lastBallTextColor: "#fff",
        playButtonColor: "#A6328D",
        playButtonBorder: "#6C1856",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "cash3midday_co",
      name: "Cash 3 Midday",
      slug: "cash3midday",
      logo: Cash3MiddayLogo,
      jackpot: "$500",
      cashValue: "$500",
      drawTime: "Daily 1:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["02", "05", "08"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#FEBC1B",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF9EC",
        gradient: ["#FFF9EC", "#FEBC1B", "#FFF9EC"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#A07500",
        lastBallGradient: ["#FFD700", "#B8860B"],
        lastBallTextColor: "#fff",
        playButtonColor: "#FEBC1B",
        playButtonBorder: "#A07500",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "cash3evening_co",
      name: "Cash 3 Evening",
      slug: "cash3evening",
      logo: Cash3EveningLogo,
      jackpot: "$500",
      cashValue: "$500",
      drawTime: "Daily 7:30 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["03", "08", "12"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#004AAD",
        borderWidth: 4,
        borderRadius: 22,
        background: "#EDF2FF",
        gradient: ["#EDF2FF", "#004AAD", "#EDF2FF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#003C87",
        lastBallGradient: ["#004AAD", "#ABB6F1"],
        lastBallTextColor: "#fff",
        playButtonColor: "#004AAD",
        playButtonBorder: "#003C87",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "powerballdouplepay_co",
      name: "Powerball Double Play",
      slug: "powerballdouplepay",
      logo: PowerballDoublePlayLogo,
      jackpot: "$10 Million",
      cashValue: "$7 Million",
      drawTime: "Mon, Wed, Sat 11:15 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["03", "11", "24", "38", "43", "21"],
      bonusNumber: "21",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#91003F",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF5F9",
        gradient: ["#FFF5F9", "#91003F", "#FFF5F9"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#91003F",
        lastBallGradient: ["#E7008A", "#FFF5F9"],
        lastBallTextColor: "#fff",
        playButtonColor: "#91003F",
        playButtonBorder: "#E7008A",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
  ];
}
