// states/AZ/games.ts
import { GameData } from "@/types/GameData";
import MegaMillionsLogo from "@/assets/logos/AZ/megamillions.svg";
import PowerballLogo from "@/assets/logos/AZ/powerball.svg";
import Fantasy5Logo from "@/assets/logos/AZ/fantasy5.svg";
import ThePickLogo from "@/assets/logos/AZ/thepick.svg";
import TripleTwistLogo from "@/assets/logos/AZ/tripletwist.svg";
import Pick3Logo from "@/assets/logos/AZ/pick3.svg";
import Pick4Logo from "@/assets/logos/AZ/pick4.svg";
import AllOrNothingLogo from "@/assets/logos/AZ/allornothing.svg";

export async function fetchArizonaGames(): Promise<GameData[]> {
  return [
    {
      id: "megamillions_az",
      name: "Mega Millions",
      slug: "megamillions",
      logo: MegaMillionsLogo,
      jackpot: "$143 Million",
      cashValue: "$66.8 Million",
      drawTime: "Tue & Fri 11:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "22", "33", "44", "55", "16"],
      bonusNumber: "16",
      powerPlay: "3x",
      result: "No Jackpot Winners | 3 Match 5 Winner | NY",
      config_ui: {
        borderColor: "#0E4CA1", // cor da borda do card
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#0E4CA1", "#FFFFFF"], // gradiente da barra
        ballGradient: ["#FFFFFF", "#BBBBBB"], //bola gradiente sera a mesma pra todo so jogos
        ballTextColor: "#101820", //cor dos números das bolas
        lastBallGradient: ["#FFD700", "#B8860B"], // se tiver bola bônus
        lastBallTextColor: "#fff", //cor dos números das bolas extra
        playButtonColor: "#0E4CA1", //cor do fundo botao
        playButtonBorder: "#EE3E33", //cor da borda do botao
        playButtonTextColor: "#fff", //cor do text do botao
        logoMarginBottom: 10,
      },
    },
    {
      id: "powerball_az",
      name: "Powerball",
      slug: "powerball",
      logo: PowerballLogo,
      jackpot: "$95 Million",
      cashValue: "$45.7 Million",
      drawTime: "Mon, Wed, Sat 10:59 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["05", "09", "22", "34", "51", "10"],
      bonusNumber: "10",
      powerPlay: "2x",
      result: "No Jackpot Winner | 1 Match 5 Winner | AZ",
      config_ui: {
        borderColor: "#C7102E",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#C7102E", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FF6666", "#B1001C"],
        lastBallTextColor: "#fff",
        playButtonColor: "#C7102E",
        playButtonBorder: "#0E4CA1",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "fantasy5_az",
      name: "Fantasy 5",
      slug: "fantasy5",
      logo: Fantasy5Logo,
      jackpot: "$75,000",
      cashValue: "$75,000",
      drawTime: "Daily 8:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["05", "12", "21", "33", "37"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#E14D2A",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF8F3",
        gradient: ["#FFF8F3", "#E14D2A", "#FFF8F3"],
        ballGradient: ["#FFF3E0", "#E67C5C"],
        ballTextColor: "#A8381E",
        lastBallGradient: ["#E7A77F", "#E14D2A"],
        lastBallTextColor: "#fff",
        playButtonColor: "#E14D2A",
        playButtonBorder: "#E14D2A",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "thepick_az",
      name: "The Pick",
      slug: "thepick",
      logo: ThePickLogo,
      jackpot: "$3.5 Million",
      cashValue: "$2.4 Million",
      drawTime: "Wed & Sat 8:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["09", "15", "24", "31", "38", "44"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#0E8157",
        borderWidth: 4,
        borderRadius: 22,
        background: "#F5FFF8",
        gradient: ["#D9F5E5", "#0E8157", "#F5FFF8"],
        ballGradient: ["#ECFFF4", "#63B17B"],
        ballTextColor: "#134B37",
        lastBallGradient: ["#B5D9C6", "#0E8157"],
        lastBallTextColor: "#fff",
        playButtonColor: "#0E8157",
        playButtonBorder: "#0E8157",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "tripletwist_az",
      name: "Triple Twist",
      slug: "tripletwist",
      logo: TripleTwistLogo,
      jackpot: "$215,000",
      cashValue: "$215,000",
      drawTime: "Daily 8:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["03", "10", "17", "23", "36", "39"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#F5AA3A",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFFDF3",
        gradient: ["#FFFDF3", "#F5AA3A", "#FFFDF3"],
        ballGradient: ["#FFEBC0", "#F5AA3A"],
        ballTextColor: "#A87506",
        lastBallGradient: ["#F5AA3A", "#FFDFB1"],
        lastBallTextColor: "#fff",
        playButtonColor: "#F5AA3A",
        playButtonBorder: "#F5AA3A",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "pick3_az",
      name: "Pick 3",
      slug: "pick3",
      logo: Pick3Logo,
      jackpot: "$500",
      cashValue: "$500",
      drawTime: "Daily 8:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "02", "03"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#4D9DE0",
        borderWidth: 4,
        borderRadius: 22,
        background: "#F7FBFF",
        gradient: ["#F7FBFF", "#4D9DE0", "#F7FBFF"],
        ballGradient: ["#F0F7FA", "#4D9DE0"],
        ballTextColor: "#29587A",
        lastBallGradient: ["#FFA500", "#FFD700"],
        lastBallTextColor: "#fff",
        playButtonColor: "#4D9DE0",
        playButtonBorder: "#4D9DE0",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
    {
      id: "pick4_az",
      name: "Pick 4",
      slug: "pick4",
      logo: Pick4Logo,
      jackpot: "$5,000",
      cashValue: "$5,000",
      drawTime: "Daily 8:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["07", "13", "19", "28"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#B892FF",
        borderWidth: 4,
        borderRadius: 22,
        background: "#F7F2FF",
        gradient: ["#F7F2FF", "#B892FF", "#F7F2FF"],
        ballGradient: ["#E3D1FF", "#B892FF"],
        ballTextColor: "#7E4A9E",
        lastBallGradient: ["#B892FF", "#E3D1FF"],
        lastBallTextColor: "#fff",
        playButtonColor: "#B892FF",
        playButtonBorder: "#B892FF",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
  ];
}
