// states/AZ/games.ts
import { GameData } from "@/types/GameData";
import MegaMillionsLogo from "@/assets/logos/AZ/megamillions.svg";
import PowerballLogo from "@/assets/logos/AZ/powerball.svg";
import Fantasy5Logo from "@/assets/logos/AZ/fantasy5.svg";
import ThePickLogo from "@/assets/logos/AZ/thepick.svg";
import TripleTwistLogo from "@/assets/logos/AZ/tripletwist.svg";
import Pick3Logo from "@/assets/logos/AZ/pick3.svg";

// MOCK AZ GAMES
export async function fetchArizonaGames(): Promise<GameData[]> {
  return [
    // Mega Millions
    {
      id: "megamillions_az",
      name: "Mega Millions",
      slug: "megamillions",
      logo: MegaMillionsLogo,
      jackpot: "$143 Million",
      cashValue: "$66.8 Million",
      drawTime: "Tue & Fri 11:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "22", "33", "44", "55", "16"],
      bonusNumber: "16",
      powerPlay: "3x",
      result: "No Jackpot Winners | 3 Match 5 Winner | NY",
      config_ui: {
        borderColor: "#0E4CA1",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#0E4CA1", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FFD700", "#B8860B"],
        lastBallTextColor: "#fff",
        playButtonColor: "#0E4CA1",
        playButtonBorder: "#EE3E33",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Powerball
    {
      id: "powerball_az",
      name: "Powerball",
      slug: "powerball",
      logo: PowerballLogo,
      jackpot: "$95 Million",
      cashValue: "$45.7 Million",
      drawTime: "Mon, Wed, Sat 10:59 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["05", "09", "22", "34", "51", "10"],
      bonusNumber: "10",
      powerPlay: "2x",
      result: "No Jackpot Winner | 1 Match 5 Winner | AZ",
      config_ui: {
        borderColor: "#C7102E",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF",
        gradient: ["#FFFFFF", "#C7102E", "#FFFFFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#101820",
        lastBallGradient: ["#FF6666", "#B1001C"],
        lastBallTextColor: "#fff",
        playButtonColor: "#C7102E",
        playButtonBorder: "#0E4CA1",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Fantasy 5
    {
      id: "fantasy5_az",
      name: "Fantasy 5",
      slug: "fantasy5",
      logo: Fantasy5Logo,
      jackpot: "$75,000",
      cashValue: "$75,000",
      drawTime: "Daily 8:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["05", "12", "21", "33", "37"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#E14D2A",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFF8F3",
        gradient: ["#FFF8F3", "#E14D2A", "#FFF8F3"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#000",
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallTextColor: "#000",
        playButtonColor: "#E14D2A",
        playButtonBorder: "#E14D2A",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // The Pick
    {
      id: "thepick_az",
      name: "The Pick",
      slug: "thepick",
      logo: ThePickLogo,
      jackpot: "$3.5 Million",
      cashValue: "$2.4 Million",
      drawTime: "Wed & Sat 8:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["09", "15", "24", "31", "38", "44"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#0E8157",
        borderWidth: 4,
        borderRadius: 22,
        background: "#F5FFF8",
        gradient: ["#D9F5E5", "#0E8157", "#F5FFF8"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#000",
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallTextColor: "#000",
        playButtonColor: "#0E8157",
        playButtonBorder: "#0E8157",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Triple Twist
    {
      id: "tripletwist_az",
      name: "Triple Twist",
      slug: "tripletwist",
      logo: TripleTwistLogo,
      jackpot: "$215,000",
      cashValue: "$215,000",
      drawTime: "Daily 8:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["03", "10", "17", "23", "36", "39"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#F5AA3A",
        borderWidth: 4,
        borderRadius: 22,
        background: "#FFFDF3",
        gradient: ["#FFFDF3", "#F5AA3A", "#FFFDF3"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#000",
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallTextColor: "#000",
        playButtonColor: "#F5AA3A",
        playButtonBorder: "#F5AA3A",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },

    // Pick 3
    {
      id: "pick3_az",
      name: "Pick 3",
      slug: "pick3",
      logo: Pick3Logo,
      jackpot: "$500",
      cashValue: "$500",
      drawTime: "Daily 8:00 PM",
      drawDate: "Wed, May 29, 2025",
      numbers: ["01", "02", "03"],
      bonusNumber: "",
      powerPlay: "",
      result: "",
      config_ui: {
        borderColor: "#4D9DE0",
        borderWidth: 4,
        borderRadius: 22,
        background: "#F7FBFF",
        gradient: ["#F7FBFF", "#4D9DE0", "#F7FBFF"],
        ballGradient: ["#FFFFFF", "#BBBBBB"],
        ballTextColor: "#000",
        lastBallGradient: ["#FFFFFF", "#BBBBBB"],
        lastBallTextColor: "#000",
        playButtonColor: "#4D9DE0",
        playButtonBorder: "#4D9DE0",
        playButtonTextColor: "#fff",
        logoMarginBottom: 10,
      },
    },
  ];
}
